from django.urls import path, include
from .views import *
urlpatterns = [
    path('user/<int:pk>', UserView.as_view()),
    path('user-create/', UserCreateView.as_view()),
    path('seller/<int:pk>', SellerView.as_view()),
    path('seller-create/', SellerCreateView.as_view()),
    path('seller-black-list/<int:pk>', SellerBlackListView.as_view()),
    path('seller-black-list-create/', SellerBlackListCreateView.as_view()),
    path('buyer-black-list/<int:pk>', BuyerBlackListView.as_view()),
    path('buyer-black-list-create/', BuyerBlackListCreateView.as_view()),
    path('buyer/<int:pk>', BuyerView.as_view()),
    path('buyer-create/', BuyerCreateView.as_view()),
    path('aucsion/<int:pk>', AucsionView.as_view()),
    path('aucsion-create/', AucsionCreateView.as_view()),
    path('aucsion-history/<int:pk>', AucsionHistoryView.as_view()),
    path('aucsion-history-create/', AucsionHistoryCreateView.as_view()),
    path('product/<int:pk>', ProductView.as_view()),
    path('product-create/', ProductCreateView.as_view()),
    path('purchase/<int:pk>', PurchaseView.as_view()),
    path('purchase-create/', PurchaseCreateView.as_view()),
    path('delivery/<int:pk>', DeliveryView.as_view()),
    path('delivery-create/', DeliveryCreateView.as_view()),
    path('expert/<int:pk>', ExpertView.as_view()),
    path('expert-create/', ExpertCreateView.as_view()),
    path('expertise/<int:pk>', ExpertiseView.as_view()),
    path('expertise-create/', ExpertiseCreateView.as_view()),
]